services:
  postgres:
    image: postgres:17.2
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - volume_postgres:/var/lib/postgresql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: initial_db

  service_pgadmin:
    image: dpage/pgadmin4:8.13.0
    ports:
      - 8080:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: aobaiwaki@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres

volumes:
  volume_postgres:
    name: volume_postgres
  volume_pgadmin:
    name: volume_pgadmin
